FORMAT: 1A
HOST: https://apidev.payplus.co.il

# payplus-new 

Polls is a simple API allowing consumers to view polls and vote in them.

## Logs [/logs/test]

### Test Logs [POST]

+ Request (application/json)
    
+ Parameters (object)
    + id (string, required)
    + created (number) - Time stamp
    + percent_off (number)
    + redeem_by (number) - Date after which the coupon can no longer be redeemed
    
+ Response 200 (application/json)